# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

APPLY_FIXES: all

DISABLE:
  - CSS
  - HTML
  - SPELL

DISABLE_LINTERS:
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - PYTHON_PYLINT
  - PYTHON_BANDIT
  - COPYPASTE_JSCPD

CPP_CPPCHECK_FILTER_REGEX_EXCLUDE: tests/

SHOW_ELAPSED_TIME: false

FILEIO_REPORTER: false
