name: "Build ReLab"
description: "Create a virtual environment, install ReLab's dependencies, and build the ReLab C++ library."
runs:
  using: "composite"
  steps:
    - name: Install CUDA
      uses: Jimver/cuda-toolkit@v0.2.20
      id: cuda-toolkit
      with:
        cuda: '12.6.0'
    - name: Install pthread library
      run: sudo apt-get install libpthread-stubs0-dev
      shell: bash
    - name: Create ReLab's virtual environment
      run: python3.12 -m venv venv-relab
      shell: bash
    - name: Install ReLab dependencies
      run:  source ./venv-relab/bin/activate && pip install .
      shell: bash
    - name: Build the C++ library and check that installation succeed
      run: source ./venv-relab/bin/activate && python3 ./scripts/test_install
      shell: bash
