---
name: "Build ReLab"
description: "Create a virtual environment, install ReLab's dependencies, and build the ReLab C++ library."
runs:
  using: "composite"
  steps:
    - name: Install CUDA
      uses: Jimver/cuda-toolkit@v0.2.20
      id: cuda-toolkit
      with:
        cuda: "12.6.0"
    - name: Install pthread library
      run: sudo apt-get install libpthread-stubs0-dev
      shell: bash
    - name: Install Poetry
      uses: Gr1N/setup-poetry@v8
    - name: Build and install ReLab
      run: poetry install
      shell: bash
    - name: Check that the installation was succeed
      run: source ./.venv/bin/activate && python3 ./relab/scripts/test_install.py
      shell: bash
