---
name: Check Pull Request Mergeability

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ReLab repository
        uses: actions/checkout@v4
      - name: Build ReLab library
        uses: ./.github/actions/build-relab
      - name: Run unit tests
        run: cd _skbuild/linux-x86_64-3.12/cmake-build/ && ctest --output-on-failure
  run_super_linter:
    runs-on: ubuntu-latest
    env:
      FILTER_REGEX_EXCLUDE: ".*.js|.*.css|.*.html"
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Clone ReLab repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TODO remove
        run: ls -la
      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.2.1
        env:
          CLANG_FORMAT_FILE_NAME: ./.clang-format
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_JSCPD: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
