name: Doxygen GitHub Pages Deploy Action

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Generate README.md
        run: apt-get install doxygen && bash ./docs/generate_doc.sh
