name: Run All Unit Tests Action

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ReLab repository
        uses: actions/checkout@v4
      - name: Clone ContinuousDelivery repository
        uses: actions/checkout@v4
        with:
          repository: TheophileChampion/ContinuousDelivery
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          path: .github/actions/
      - name: TODO remove
        run: ls .github/actions/
      - name: Build ReLab
        uses: ./.github/actions/build-relab.yaml
      - name: Run unit tests
        run: cd build && ctest --output-on-failure
