name: Run All Unit Tests Action

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ReLab repository
        uses: actions/checkout@v4
      - name: Build ReLab
        uses: TheophileChampion/ContinousDelivery-build-relab@v0.1.1
      - name: Run unit tests
        run: cd build && ctest --output-on-failure
